### ISSUE TITLE
SMF MetricTicks type inconsistency

### ISSUE THREAD

**Issue by scisci** [gomidi/midi#10]
Hi, I was just trying to follow some example code you had and I got the error

```
cannot use tpq.Ticks4th() (type uint16) as type uint32 in argument to wr.SetDelta
```

I understand why, but it seems wrong for Ticks4th to return a uint16, but all of the other Ticks methods return a uint32.

**Comment by metakeule** [comment]
@scisci 
Yes you are right! I will decouple `func (MetricTicks) Number()` from `func (MetricTicks) Ticks4th()` and will make the latter return an `uint32`.  Thanks for pointing this out.
