### ISSUE TITLE
There is any documentation to support multiplateform and even aLSA + Jack on Linux ?

### ISSUE THREAD

**Issue by mikefaille** [gomidi/midi#19]
I want to create an autosampler in golang but I will need more information for the mutiplateform support. 

Any documentation or hint is available ? If not, I suggest to have an example to get it works.

**Comment by metakeule** [comment]
There is an example on the README file, there are examples inside the examples folders, there is the normal Go documentation, so what are you asking for. Pick the rtmididrv or midicatdrv or portmididrv and there you go - all of them are multiplattform (windows, linux, macos).

For jack, pick the a2midid brigde so you can bridge between jack midi and alsa midi.

**Comment by mikefaille** [comment]
Awesome ! Yes, I did make it works on Linux. I see the example. I believed
we must add parameters to support multiplatform but then it's nice for the
transparent compatibility ! I'm happy !
