### ISSUE TITLE
unable to parse seemingly valid midi file

### ISSUE THREAD

**Issue by jsphweid** [gomidi/midi#20]
In Lakh dataset `lmd_full/0/0016ddb29c16d94c366d72b442ee1c78.mid` cannot be read without panic. I tried reading it in a python lib (using `mido`) and it worked fine. Open in VLC and played just fine. I'm not immediately sure what the issue is here. I'm not familiar with the specifics of MIDI files. I might have some time to deep dive real soon though. In the meantime, any idea what could be happening here?

```
panic: must not happen: invalid canary  47
```

Log file attached. Can't upload midi file but the whole dataset is accessible [here](https://colinraffel.com/projects/lmd/).
[crash.log](https://github.com/gomidi/midi/files/9016268/crash.log)

**Comment by jsphweid** [comment]
So I did a bit of digging and discovered the issue seems to be that the running status gets reset when it shouldn't _I think_.

Here are the events leading to the crash...
```
note on
00 delta
47 note
5c velocity

04 delta
ff meta message
01 text type
02 2 bytes
25 "%"
2b "+"

16 delta
47 note  -- CRASHES HERE BECAUSE RUNNING STATUS IS 0
00 velocity

00 delta
43 note
00 velocity

00 delta
ff meta
2f 00 end of track
```

Looking at some other midi parsers:
https://github.com/vishnubob/python-midi/blob/master/src/fileio.py
https://github.com/mido/mido/blob/main/mido/midifiles/midifiles.py

It appears that they don't reset the running status mid-track. When encountering meta messages, they simple avoid changing the running status but not explicitly clear it. But [this lib does](https://github.com/gomidi/midi/blob/master/v2/internal/runningstatus/runningstatus.go#L67-L71) and that's what causes the issue.

Reading more about running status on here:
http://midi.teragonaudio.com/tech/midispec/run.htm

Maybe running status should only be cleared when "Buffer is cleared when a System Common Category Status (ie, 0xF0 to 0xF7) is received." In other words 0xFF should _not_ clear running status.

Thoughts?

**Comment by metakeule** [comment]
@jsphweid 

I rechecked it. The library is conforming to the SMF specs. Your link refers to live midi which is differs there.

Maybe I'll add an option to relax that. But I prefer to be strict by default (conform to the specs).

Apart from that, the development of this lib takes place at https://gitlab.com/gomidi/midi so I am closing this one and disabling issues here on github once and for all.

Thanks for your input!

Best regards
Marc
